version: 0.2

env:
  variables:
  EXPO_USERNAME: <shubham21>
phases:
  install:
    runtime-versions:
      nodejs: 10
  
  pre_build:
    commands:
      - npm install
      - echo "Installing Expo"
      - npm install -g expo-cli
      - expo --version
      - export EXPO_CLI_PASSWORD=$(aws ssm get-parameter --name "Shastri@1994" --region <ap-south-1> --query 'Parameter.Value' --output text)
      - npx expo login --non-interactive -u ${EXPO_USERNAME}
 # build:
  #  commands:
   #   - echo "Executing build"
   #   - expo build:android -t apk
 post_build:
    commands:
      - echo "publishing to expo default channel"
      - npx expo publish --non-interactive
