version: 0.2

phases:

    INSTALL:
        runtime-versions:
            nodejs: 10
        commands:
            - npm install


    PRE_BUILD:
      commands:
        - npm install --quiet --global expo-cli
        - >
          if [ -f yarn.lock ]; then
            yarn
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install
          fi
    BUILD:
      commands:
        - expo build:android
artifacts:
    baseDirectory: android-build
