version: 0.2

phases:
  install:
    commands:
     - echo "install phase started"
     - npm install
     - echo "install phase ended"
  pre_build: 
    commands:
     - npm install
     - echo "Installing Expo"
     - npm install -g expo-cli
     - expo --version	
     - echo "pre_build test phase started"
     - echo " unit test"
     - npm test
     - echo "unit test ended"
  build:
    commands:
     - echo "build phase started"
     - echo "build complete"
  post_build:
    commands:
      - expo login -u 'shubham21' -p 'Shastri@1994' 
      - echo "publishing to expo default channel"
      - npx expo publish --non-interactive

artifacts:
    baseDirectory: android-build

