version: 0.2
phases:
  install:
    commands:
     - echo "Installing phase started..."
     - npm install 
     - echo "install phase ended"

  pre_build: 
    commands:
      - mkdir expo-apps/android/ #not required
      - npm install
      - expo login --username [EXPO_USERNAME] --password [EXPO_PASSWORD]
      - expo publish
      - expo fetch:android:keystore
  build:
    commands:  
      - cp /usr/src/app/shExpoBuild/buildAndroid.sh ./buildAndroid.sh
      - ./buildAndroid.sh b30f2c1e368f4237b9aa037ffcd1d4eb b121f416f3024a76bb065ec2b805160d sayeed99 Iamsocool@99 ./Parkirin.jks QHNheWVlZDk5L1Bhcmtpcmlu apk

  post_build:
    commands:
      - echo "Updating files to s3 bucket..."
      - aws s3 cp --recursive --acl public-read ./build s3://react-native-1/public/
artifacts:
  files:
    - '**/*'
  base-directory: build
    