version: 0.2

phases:
  install:
    commands:
     - echo "Installing phase started..."
     - npm install
     - echo "install phase ended"

  pre_build: 
    commands:
     - echo "Installing turtle"
     - npm install -g turtle-cli --unsafe-perm
     - turtle --version	
     - echo "pre_build test phase started"
     - echo " unit test"
     - npm test
     - echo "unit test ended"

  build:
    commands:
     #- aws configure
     - echo "build phase started..."
     #- npx expo login -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) 
     - npx expo login -u 'shubham21' -p 'Shastri@1994'
     - turtle build:android
     #- expo build:android
     - echo "build complete"
  post_build:
    commands:
      - echo "Updating files to s3 bucket..."
      - aws s3 cp --recursive --acl public-read ./build s3://react-native-1/public/
     # - aws s3 cp build s3://react-native-1 --recursive
     # - aws s3 sync build/ s3://react-native-1
artifacts:
  files:
    - '**/*'
  base-directory: build
    