version: 0.2
env:
  variables:
    JAVA_8: (alternatives --display java | grep 'family java-8-openjdk' | cut -d' ' -f1)
phases:
  install:
    commands:
     - echo "Installing phase started..."
     - npm install 
     - echo "install phase ended"

  pre_build: 
    commands:
     - echo "Installing turtle"
     - npm install -g turtle-cli --unsafe-perm=true --allow-root
     - turtle --version	
     - npm install -g expo-cli
     - npx expo login -u 'shubham21' -p 'Shastri@1994'
     - echo "pre_build test phase started"
     - echo " unit test"
     - npm test
     - echo "unit test ended"

  build:
    commands:  
     #- apt-get update
     
     #- apt-get install -y openjdk-8-jdk
     #- apt-get install -y openjdk-8-jre 
     #- update-alternatives --config java
     #- update-alternatives --config javac
     #- update-alternatives --set java $JAVA_8
     #- java -version
     #- update-alternatives --set java /usr/lib/jvm/jdk8_version/bin/java
     - echo "build phase started..."
     #- npx expo login -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) 
     - turtle build:android 
     - echo "build complete"

  post_build:
    commands:
      - echo "Updating files to s3 bucket..."
      - aws s3 cp --recursive --acl public-read ./build s3://react-native-1/public/
     # - aws s3 cp build s3://react-native-1 --recursive
     # - aws s3 sync build/ s3://react-native-1
artifacts:
  files:
    - '**/*'
  base-directory: build
    