version: 0.2

phases:
  install:
    commands:
     - echo "install phase started..."
     - npm install
     - echo "install phase ended"
  pre_build: 
    commands:
     - npm install
     - echo "Installing Expo"
     - npm install -g expo-cli
     - expo --version	
     - echo "pre_build test phase started"
     - echo " unit test"
     - npm test
     - echo "unit test ended"
  build:
    commands:
     - echo "build phase started..."
     - expo login -u 'shubham21' -p 'Shastri@1994'
     - expo build:android
     - echo "build complete"
  post_build:
    commands:
      - echo "Updating files to s3 bucket..."
      - aws s3 cp --recursive --acl public-read ./build s3://react-native-1/public/
     # - aws s3 cp build s3://react-native-1 --recursive
     # - aws s3 sync build/ s3://react-native-1
artifacts:
  files:
    - '**/*'
  base-directory: build
    